import type { ProductCandidate, ProductSearchIntent } from "../productSourcingTypes";
import type { ProductSupplierConnector } from "../productSupplierConnector";

/** Dev/demo catalog — indicative prices only, not live supplier data. */
const MOCK_CATALOG: Omit<ProductCandidate, "id" | "matchReason">[] = [
  {
    sourceType: "supplier_api",
    supplierName: "Mock Elektro Veľkoobchod",
    brand: "ABB",
    productName: "ABB zásuvka 230V biela",
    productCode: "ABB-ZAS-230-W",
    category: "socket",
    unit: "ks",
    netUnitPrice: 4.8,
    currency: "EUR",
    vatPercent: 20,
    availability: "in_stock",
    priceValidAt: new Date().toISOString(),
    confidence: "indicative",
    needsReview: true,
    priceTier: "standard",
  },
  {
    sourceType: "supplier_api",
    supplierName: "Mock Elektro Veľkoobchod",
    brand: "Schneider Electric",
    productName: "Schneider zásuvka Unica 230V",
    productCode: "SE-UNI-ZAS",
    category: "socket",
    unit: "ks",
    netUnitPrice: 6.2,
    currency: "EUR",
    vatPercent: 20,
    availability: "in_stock",
    priceValidAt: new Date().toISOString(),
    confidence: "indicative",
    needsReview: true,
    priceTier: "premium",
  },
  {
    sourceType: "supplier_api",
    supplierName: "Mock Elektro Veľkoobchod",
    brand: "Hager",
    productName: "Hager zásuvka economy 230V",
    productCode: "HG-ECO-Z",
    category: "socket",
    unit: "ks",
    netUnitPrice: 3.1,
    currency: "EUR",
    vatPercent: 20,
    availability: "limited",
    priceValidAt: new Date().toISOString(),
    confidence: "indicative",
    needsReview: true,
    priceTier: "economy",
  },
  {
    sourceType: "supplier_api",
    supplierName: "Mock Elektro Veľkoobchod",
    brand: "ABB",
    productName: "ABB vypínač radový",
    productCode: "ABB-VYP-1",
    category: "switch",
    unit: "ks",
    netUnitPrice: 5.4,
    currency: "EUR",
    vatPercent: 20,
    availability: "in_stock",
    priceValidAt: new Date().toISOString(),
    confidence: "indicative",
    needsReview: true,
    priceTier: "standard",
  },
  {
    sourceType: "supplier_api",
    supplierName: "Mock Elektro Veľkoobchod",
    brand: "Generic LED",
    productName: "LED pás 24V 10W/m",
    productCode: "LED-24-10",
    category: "led_strip",
    unit: "m",
    netUnitPrice: 7.5,
    currency: "EUR",
    vatPercent: 20,
    availability: "in_stock",
    priceValidAt: new Date().toISOString(),
    confidence: "indicative",
    needsReview: true,
    priceTier: "standard",
    description: "Overiť CCT, IP a výkon — špecifikácia z výkresu často chýba.",
  },
  {
    sourceType: "supplier_api",
    supplierName: "Mock Elektro Veľkoobchod",
    brand: "Generic LED",
    productName: "LED hliníkový profil + difúzor",
    productCode: "LED-PROF-ALU",
    category: "led_profile",
    unit: "m",
    netUnitPrice: 9.2,
    currency: "EUR",
    vatPercent: 20,
    availability: "in_stock",
    priceValidAt: new Date().toISOString(),
    confidence: "indicative",
    needsReview: true,
    priceTier: "standard",
  },
  {
    sourceType: "supplier_api",
    supplierName: "Mock Elektro Veľkoobchod",
    brand: "Mean Well",
    productName: "LED driver 24V 100W",
    productCode: "MW-24-100",
    category: "led_driver",
    unit: "ks",
    netUnitPrice: 28,
    currency: "EUR",
    vatPercent: 20,
    availability: "unknown",
    priceValidAt: new Date().toISOString(),
    confidence: "indicative",
    needsReview: true,
    priceTier: "standard",
  },
  {
    sourceType: "supplier_api",
    supplierName: "Mock Elektro Veľkoobchod",
    brand: "Kopp",
    productName: "Inštalačná krabica podomietková",
    productCode: "KP-BOX-1",
    category: "installation_box",
    unit: "ks",
    netUnitPrice: 0.85,
    currency: "EUR",
    vatPercent: 20,
    availability: "in_stock",
    priceValidAt: new Date().toISOString(),
    confidence: "indicative",
    needsReview: false,
    priceTier: "economy",
  },
  {
    sourceType: "supplier_api",
    supplierName: "Mock Elektro Veľkoobchod",
    brand: "CYKY",
    productName: "CYKY 3×2,5 (cena za m — treba zameranie)",
    productCode: "CYKY-3X25",
    category: "cable",
    unit: "m",
    netUnitPrice: 1.35,
    currency: "EUR",
    vatPercent: 20,
    availability: "in_stock",
    priceValidAt: new Date().toISOString(),
    confidence: "indicative",
    needsReview: true,
    priceTier: "standard",
    description: "Dĺžka musí byť zameraná — jednotková cena je len orientačná.",
  },
  {
    sourceType: "supplier_api",
    supplierName: "Mock Elektro Veľkoobchod",
    brand: "Hager",
    productName: "Rozvodnica / ističová sada (orientačne)",
    productCode: "HG-DB-SET",
    category: "distribution_board",
    unit: "set",
    netUnitPrice: 420,
    currency: "EUR",
    vatPercent: 20,
    availability: "unknown",
    priceValidAt: new Date().toISOString(),
    confidence: "needs_review",
    needsReview: true,
    priceTier: "standard",
  },
];

function matchesIntent(row: (typeof MOCK_CATALOG)[number], intent: ProductSearchIntent): boolean {
  if (row.category === intent.category) return true;
  const hay = `${row.productName} ${row.brand ?? ""} ${row.category}`.toLowerCase();
  return intent.keywords.some((k) => hay.includes(k.toLowerCase()));
}

export function createMockSupplierConnector(
  countryCodes: string[] = ["SK", "CZ", "AT", "DE"]
): ProductSupplierConnector {
  return {
    id: "mock_elektro",
    name: "Mock Elektro Veľkoobchod",
    countryCodes,
    supportsSearch: true,
    supportsPrice: true,
    supportsAvailability: true,
    async searchProducts(intent) {
      return MOCK_CATALOG.filter((row) => matchesIntent(row, intent)).map((row, i) => ({
        ...row,
        id: `mock_${row.productCode ?? i}_${intent.takeoffItemId}`,
        matchReason: `Mock katalóg · kategória ${intent.category}`,
      }));
    },
  };
}
