export {
  createQuoteFromProject,
  upsertQuoteFromProject,
  createStandaloneQuote,
  saveQuote,
  setQuoteStatus,
  removeQuote,
  listQuotesForWorkspace,
  listQuotesForWorkspaceEnsured,
  syncMissingQuotesFromProjects,
  syncQuotesFromProjectLifecycle,
  syncQuoteStatusesFromProjects,
  getQuote,
  hasQuoteAccess,
  type QuoteDoc,
  type QuoteStatus,
  type CreateQuoteInput,
  type UpdateQuoteInput,
} from "./quoteService";
